---
# mon tasks

- name: Copy ceph.client.admin.keyring
  copy:
    src: etc/ceph/ceph.client.admin.keyring
    dest: /etc/ceph/ceph.client.admin.keyring
    owner: ceph
    group: ceph

- name: Copy ceph.mon.keyring
  copy:
    src: tmp/ceph.mon.keyring
    dest: /tmp/ceph.mon.keyring
    owner: ceph
    group: ceph

- name: Generate monmaptool
  shell: monmaptool --create --add {{ ansible_hostname }} {{ ansible_eth1['ipv4']['address'] }} --fsid {{ fsid }} /tmp/monmap
  register: generate_monmap
  args:
    creates: /tmp/monmap
  become: true
  become_user: ceph

- name: Create ceph-mon fs
  shell: ceph-mon --mkfs -i {{ ansible_hostname }} --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring
  register: create_ceph_mon_fs
  args:
    creates: /var/lib/ceph/mon/ceph-mon1
  become: true
  become_user: ceph

- name: Start ceph-mon service
  service:
    name: ceph-mon@mon1
    state: started
# generate monmaptool monmaptool --create --add {{ ansible_hostname }} {{ ansible_eth1['ipv4']['address'] }} --fsid {{ fsid }} /tmp/monmap
# mkfs ceph-mon ceph-mon --mkfs -i {{ ansible_hostname }} --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring
